apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: replica-replica
    labels:
        app: myapp
        type: front-end
spec:
    replicas: 4
    selector:
        matchLabels:
            type: front-end
    template:
        metadata:
            labels:
                name: myapp
                type: front-end
        spec:
            containers:
                - name: nginx
                  image: nginx
