apiVersion: v1
kind: Pod
metadata:
    name: pod-with-sa
    labels:
        type: learn-k8s
spec:
    containers:
        - name: secret-user
          image: nginx
    serviceAccountName: new-sa
    automountServiceAccountToken: false #If don't want sa automatically

