apiVersion: v1
kind: Pod
metadata:
    name: pod-with-defined-limited-resource
    labels:
        type: learn-k8s
spec:
    containers:
        - name: resources-given
          image: nginx
          resources:
            requests:
                memory: "2Gi"
                cpu: 2
            limits:
                memory: "3Gi"
                cpu: 2
