apiVersion: v1
kind: Pod
metadata:
    name: tolerant-pod
spec:
    tolerations:
        - key: "app"
          operator: "Equal"
          value: "blue"
          effect: "NoSchedule"
    containers:
        - name: toleration-learn
          image: nginx
