apiVersion: v1
kind: Pod
metadata:
    name: pod-using-config-envfrom
    labels:
        type: learn-k8s
spec:
    containers:
        - name: config-user
          image: nginx
          envFrom:
            - configMapRef:
                name: config-map

