apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
      run: nodeselector-pod
  name: nodeselector-pod
spec:
  containers:
  - image: nginx
    name: affinity-pod
    resources: {}
  nodeSelector:
    size: Large
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
#And also have a node labelled for size:large
#k label nodes my-node size=Large
#NodeSelector limitation is; it does not support and, or, not in labels.
