apiVersion: v1
kind: Pod
metadata:
    name: pod-using-secret
    labels:
        type: learn-k8s
spec:
    containers:
        - name: secret-user
          image: nginx
          env:
            - name: MY_USER
              valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: Username
            - name: MY_PASS
              valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: Password

