apiVersion: v1
kind: Pod
metadata:
    name: pod-using-secretref
    labels:
        type: learn-k8s
spec:
    containers:
        - name: secret-user
          image: nginx
          envFrom:
                - secretRef:
                    name: app-secret
